services:
  qr-code-generator:
    image: qr-code-generator
    build: .
    user: "10000:1003"  # webadmin:psacln
    ports:
      - "5010:5010"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    