version: '3.8'

services:
  qr-code-generator:
    image: qr-code-generator
    build: .
    ports:
      - "5010:5010"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    
